Review
Goodluck5956/projectreview pull request #1
Opened 2021-07-08 18:27 UTC by Goodluck5956

- A new branch was added to my initial project
- A pull request was generated for code review
- new documents like .gitignore, linters, and README was added

2021-07-08 21:02 UTC, Goodluck5956 commented
- Line indentation for the CSS styling was all corrected
- Best practice of HTML and CSS was applied which fix most linter errors.

2021-07-08 22:33 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @Goodluck5956 :wave:

__You've really done an amazing job so far:__

- You've used the correct GitHub Flow :+1: 
- Your PR title and summary look good :+1: 
- All linter checks are running with no error :100: 

__However, you need to make some required changes before moving on to the next assignment.__
> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it :blush: 

### **Required Changes** :recycle: 
Please read carefully the comments under the review.

### **Optional Changes** :zap: 
_Every comment with the **OPTIONAL** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


* * *
**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@teekaytech) so I can be notified about your comments and respond._

*REMINDER: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).*

_**Please make the required changes and submit another review request when you are done.**_

* * *

_Reviewed by:_ [**Taofeek Olalere**](https://github.com/teekaytech)
__Cheers & Happy coding :smiley:__

2021-07-08 22:33 UTC, teekaytech commented on README.md
>  james project review
Thank you for making some comments about this project here: https://github.com/Goodluck5956/projectreview/pull/1#issuecomment-876743606 :+1: 

However, it looks like you did not really get the main purpose of this project.

Since this project is about you performing a code review on one of your projects and applying HTML & CSS best practices introduced by the [How to give a code review?](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md) lesson,  the focus is on "how" well you communicate and perform the code review, by being friendly, clear, polite, professional and using the GitHub code review features appropriately. This means that you're not expected to actually fix the bug or solve the problems with the project, but review the project.

Therefore, you are expected to:
- [ ] submit a review in the Pull Request you opened utilizing the "Review changes" feature from GitHub. Check how to use GitHub Features [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md#how-to-use-github-features)
- [ ] write at least 2 comments in the review.
- [ ] use the [GitHub inline comments feature](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) at least once to leave review comments. You should leave the comment under a line or block of code that fits the context the comment is about.

Other things to take note of include:
- [ ] Ensure that you phrase your comments politely, as suggestions instead of orders.
  For example:
  - **This is a polite suggestion:** _"I think it would be better to use semantic tags"_
  - **This reads as an order:** _"Use semantic tags"_
- [ ] Also, you should always include an explanation, a "why", for each requested change. 
  For example:
  - **This is a well-explained request:** _Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible_
  - **This request lacks a "why":** _Why don't you use an article tag here instead of a div?_
- [ ] Your comments should also be clear and easy to understand. 
  For Example:
  - **This is a clear comment:** _The README's "Built With" and "Getting Started" sections are currently empty. Why don't you add content, listing the technology used in the project and how to run it, to them so your README is more informative and professional?_
  - **This is a vague comment:** _The README is not descriptive, why don't you make it better?_

------
_Examples of bugs/issues/errors you may check for when performing the review:_
- Lack of semantic HTML tags use.
- Not applying HTML & CSS best practices correctly.
- Bugs missed the first time the project was built, etc

2021-07-09 20:37 UTC, Goodluck5956 commented on index.html
> +  <body>
### Great job so far💪💪 but I would suggest you adjust the following code😫😫

-  I will suggest a header element be added before the main element because:

1. It's advisable to follow semantic HTML and CSS rules✌✌
2. It show's professionalism✔✔

2021-07-09 20:53 UTC, Dipeshtwis approved these changes
# Hi @Goodluck5956, 

### Status: Approved ✔️

:+1:  Professional repo, with good commit message and PR title, keep up the good work :muscle:
:+1: You have implemented all the changes requested by the previous reviewer. Well Done.

Your project is complete!  There are some optional changes I've suggested to you to make your project best, other than that nothing else to say.
Congratulations! 🎉 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- A nice tip to consolidate your reviews under a single summary is to click the "Start a review" button when adding the first review comment. This helps to house all your inline comment under one single summary like this current review. :wink:


**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Dipesh Kumar_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-09 20:53 UTC, Dipeshtwis commented on index.html
> +       <img src="https://citas.in/media/authors/chris-brown.jpeg" alt="photo" id="image">
[OPTIONAL]
This is an example inline comment. :slightly_smiling_face:
- You can see how it's under the main summary above and point to a specific part of the code where you want to suggest changes or just comment on it generally. :wink:

2021-07-09 23:09 UTC, merged